# Generated by Django 4.2.9 on 2024-01-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_imagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="account_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imagemodel",
            name="name",
            field=models.CharField(default="name", max_length=255),
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(upload_to="images/r_img"),
        ),
    ]
